// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("0.1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0.0")>]
[<assembly: AssemblyTitleAttribute("Gotcha.Core")>]
[<assembly: AssemblyDescriptionAttribute("Core Gotcha Game Engine")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "0.1.0.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0.0"
    let [<Literal>] AssemblyTitle = "Gotcha.Core"
    let [<Literal>] AssemblyDescription = "Core Gotcha Game Engine"
